// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iviaxxfodvwqjiiomzkl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml2aWF4eGZvZHZ3cWppaW9temtsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYwNzY2MjEsImV4cCI6MjA1MTY1MjYyMX0.dcQOocrwwv5_n_FCQtStgF-lzlu1hNsUDDvf6HBfgUc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);